apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31334
  selector:
    app: registry
  type: NodePort
